spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/notes-db
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
